name: Build Container Image
on:
  push:
    branches:
      - dev
      - release_*
    tags:
      - v*
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # https://stackoverflow.com/questions/59810838/how-to-get-the-short-sha-for-the-github-workflow
      - name: Set outputs
        id: commit
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Set branch name
        id: branch
        run: |
          if [[ "$GITHUB_REF" == "refs/tags/"* ]]; then
            echo "name=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
          elif [[ "$GITHUB_REF" == "refs/heads/dev" ]]; then
            echo "name=dev" >> $GITHUB_OUTPUT
          elif [[ "$GITHUB_REF" == "refs/heads/release_"* ]]; then
            echo "name=${GITHUB_REF#refs/heads/release_}-auto" >> $GITHUB_OUTPUT
          fi
        shell: bash
      - name: Build container image
        run: docker build . --build-arg GIT_COMMIT=$(git rev-parse HEAD) --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') --build-arg IMAGE_TAG=${{ steps.branch.outputs.name }}.ci -t acr.aigene.org.cn/ops/lscp-galaxy:${{ steps.branch.outputs.name }}.ci -f .k8s_ci.Dockerfile
      - name: Login to acr
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.ACR_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.ACR_PWD }}
          DOCKER_REGISTRY_URL: acr.aigene.org.cn
      - name: Push to acr with branch name
        uses: actions-hub/docker@master
        with:
          args: push acr.aigene.org.cn/ops/lscp-galaxy:${{ steps.branch.outputs.name }}.ci
